version: "3"
services:
  development:
    container_name: "challenge-charlie"
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - /app/node_modules
    command: npm run dev